spring:
  datasource:
    url: jdbc:oracle:thin:@47.95.203.87:1521:helowin
    username: haha
    password: qwer#1234#iscas
    driver-class-name: oracle.jdbc.OracleDriver


### mybatis
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml



